# Generated by Django 5.2.15 on 2026-06-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Fan')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('option1', models.CharField(max_length=200, verbose_name='Variant 1')),
                ('option2', models.CharField(max_length=200, verbose_name='Variant 2')),
                ('option3', models.CharField(max_length=200, verbose_name='Variant 3')),
                ('option4', models.CharField(max_length=200, verbose_name='Variant 4')),
                ('correct_answer', models.CharField(max_length=200, verbose_name="To'g'ri javob")),
            ],
        ),
    ]
